# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20170103185511 on 2017-01-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_auto_20170117_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='questions_answered',
        ),
        migrations.AddField(
            model_name='profile',
            name='votes',
            field=models.ManyToManyField(related_name='votes', to='meet.Vote'),
        ),
    ]
