# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20170103185511 on 2017-01-17 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_vote_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
