# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20170103185511 on 2017-01-17 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_auto_20170117_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='num_votes',
            field=models.IntegerField(default=0),
        ),
    ]
